# Environment Variable Setting
################################################################################
dotenv_path: null


# Logging Setting
################################################################################
log_root_dir: logs/electricity

# experiment_name: would be used to create log_dir = log_root_dir/experiment_name/
experiment_name: zero_shot_cot

# test_jsonl_filename: would be used to create test_jsonl_path = log_dir/test_jsonl_filename;
#   if set to null, the experiment_name would be used
test_jsonl_filename: null

# Number of rounds you want to test. min, max, avg. accuracy will be reported if multiple rounds.
test_rounds: 1


# Workflow Setting
################################################################################
workflow:
  module_path: pikerag.workflows.qa
  class_name: QaWorkflow


# Testing Suite Setting
################################################################################
test_loading:
  module: pikerag.utils.data_protocol_utils
  name: load_testing_suite
  args:
    filepath: data/electricity/qa_output_augmented.jsonl


# Prompt Setting
################################################################################
qa_protocol:
  module_path: pikerag.prompts.qa
  attr_name: generation_qa_protocol


# LLM Setting
################################################################################
llm_client:
  module_path: pikerag.llm_client
  # available class_name: AzureMetaLlamaClient, AzureOpenAIClient, HFMetaLlamaClient, StandardOpenAIClient
  class_name: StandardOpenAIClient
  args: {}

  llm_config:
    model: qwen-plus-latest
    temperature: 0

  cache_config:
    location_prefix: null
    auto_dump: True

# Retriever Setting
################################################################################
retriever:
  module_path: pikerag.knowledge_retrievers
  class_name: BaseQaRetriever
  args: {}


# Evaluator Setting
################################################################################
evaluator:
  metrics:
    - ExactMatch
    - F1
    - Precision
    - Recall
    - LLM
